### ISSUE TITLE
Handle missing example summary and description in automated generated samples

### ISSUE THREAD

**Issue by silverbullettruck2001** [Rhosys/openapi-explorer#77]
Whenever I click on an individual `path` in the left nav it generates this error.  Do you know what I need to do to fix this:

```
index.03831851.js:384 Uncaught (in promise) TypeError: Cannot read properties of null (reading '::TITLE')
    at index.03831851.js:384:10678
    at Array.map (<anonymous>)
    at gu (index.03831851.js:384:10657)
    at F4.responseTemplate (index.03831851.js:400:12936)
    at F4.render (index.03831851.js:400:12517)
    at F4.update (index.03831851.js:199:1368)
    at F4.performUpdate (index.03831851.js:177:4833)
    at F4._enqueueUpdate (index.03831851.js:177:4483)
```

Here is a screenshot of the section of code that it is failing in as well as the block:
![image](https://user-images.githubusercontent.com/26559157/181489123-34c90d87-bd27-4ee1-bbf1-020c156db58e.png)

```
    function gu(e, t, r, n, i=!0, o=!0, a, u=!1) {
        const s = n || "application/json"
          , l = [];
        if (e)
            for (const m in e) {
                let w = ""
                  , y = "json";
                if (s.toLowerCase().includes("json")) {
                    if (a === "text")
                        w = typeof e[m].value == "string" ? e[m].value : JSON.stringify(e[m].value, void 0, 2),
                        y = "text";
                    else if (w = e[m].value,
                    typeof e[m].value == "string")
                        try {
                            const x = e[m].value.replace(/([\w]+)(:)/g, '"$1"$2').replace(/'/g, '"');
                            w = JSON.parse(x),
                            y = "json"
                        } catch {
                            y = "text",
                            w = e[m].value
                        }
                } else
                    w = e[m].value,
                    y = "text";
                l.push({
                    exampleId: m,
                    exampleSummary: e[m].summary || m,
                    exampleDescription: e[m].description || "",
                    exampleType: s,
                    exampleValue: w,
                    exampleFormat: y
                })
            }
        else if (t) {
            let m = ""
              , w = "json";
            if (s.toLowerCase().includes("json")) {
                if (a === "text")
                    m = typeof t == "string" ? t : JSON.stringify(t, void 0, 2),
                    w = "text";
                else if (typeof t == "object")
                    m = t,
                    w = "json";
                else if (typeof t == "string")
                    try {
                        m = JSON.parse(t),
                        w = "json"
                    } catch {
                        w = "text",
                        m = t
                    }
            } else
                m = t,
                w = "text";
            l.push({
                exampleId: "Example",
                exampleSummary: "",
                exampleDescription: "",
                exampleType: s,
                exampleValue: m,
                exampleFormat: w
            })
        }
        if (l.length)
            return l;
        if (r && r.example)
            return [{
                exampleId: "Example",
                exampleSummary: "",
                exampleDescription: "",
                exampleType: s,
                exampleValue: r.example,
                exampleFormat: s.toLowerCase().includes("json") && typeof r.example == "object" ? "json" : "text"
            }];
        const d = {
            includeReadOnly: i,
            includeWriteOnly: o,
            skipExampleStrings: u,
            xml: s.toLowerCase().includes("xml")
        }
          , v = T4(r, d);
        return !v || !s.toLowerCase().includes("json") && !s.toLowerCase().includes("text") && !s.toLowerCase().includes("*/*") && !s.toLowerCase().includes("xml") ? [{
            exampleId: "Example",
            exampleSummary: "",
            exampleDescription: "",
            exampleType: s,
            exampleValue: "",
            exampleFormat: "text"
        }] : v.map((m,w)=>{
            const y = m["::TITLE"] || `Example ${w + 1}`
              , x = m["::DESCRIPTION"] || "";
            Kg(m);
            let E = "";
            return s.toLowerCase().includes("xml") ? E = w4(m, {
                declaration: !0,
                indent: "    "
            }) : E = a === "text" ? JSON.stringify(m, null, 8) : m,
            {
                exampleId: `Example-${w}`,
                exampleSummary: y,
                exampleDescription: x,
                exampleType: s,
                exampleFormat: s.toLowerCase().includes("xml") ? "text" : a,
                exampleValue: E
            }
        }
        ).filter(m=>m)
    }
```

**Comment by wparad** [comment]
It looks like there is a bad `example` in the spec (or a good example that we aren't handling correctly). I'm going to throw some protection on it in any case to prevent others from running into this.
